# Generated by Django 5.1.2 on 2024-10-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oldCart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
