# Generated by Django 5.1.2 on 2024-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_shipped_alter_shippingaddress_shippingaddress2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateShipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
